global:
  scrape_interval: 10s

  external_labels:
    monitor: 'masstransit'

scrape_configs:
  - job_name: 'masstransit'
    scheme: http
    enable_http2: false
    static_configs:
      - targets: ['host.docker.internal:5160']
  
  - job_name: 'prometheus'
    enable_http2: false
    static_configs:
      - targets: ['localhost:9090']